//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoadonCustomer
    {
        public int id_customer { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public Nullable<System.DateTime> born_date { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> bonus_points { get; set; }
        public string password { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public Nullable<int> house_number { get; set; }
    }
}
