//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_shoesEntities5 : DbContext
    {
        public DB_shoesEntities5()
            : base("name=DB_shoesEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<CustomersToOrder> CustomersToOrders { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<MoadonCustomer> MoadonCustomers { get; set; }
        public virtual DbSet<OrdersFromBranch> OrdersFromBranches { get; set; }
        public virtual DbSet<OrdersFromStock> OrdersFromStocks { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<ShoeDescription> ShoeDescriptions { get; set; }
        public virtual DbSet<Sho> Shoes { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
