//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersFromBranch
    {
        public int id_order { get; set; }
        public int from_branch { get; set; }
        public int to_branch { get; set; }
        public System.DateTime order_date { get; set; }
        public int id_cust { get; set; }
        public int id_shoe { get; set; }
        public int size { get; set; }
        public string color { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Branch Branch1 { get; set; }
        public virtual CustomersToOrder CustomersToOrder { get; set; }
        public virtual Sho Sho { get; set; }
    }
}
