//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int id_stock { get; set; }
        public int id_shoe { get; set; }
        public int id_branch { get; set; }
        public int size { get; set; }
        public string color { get; set; }
        public int amount { get; set; }
        public Nullable<int> available_amount { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Sho Sho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
